name: Validate implementation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install valgrind
      run: sudo apt-get install valgrind
    - name: Test implementation and leaks
      run: make leaktest
